let
    Source = #"Team Season Stats",
    #"Grouped Rows" = Table.Group(Source, {"Year"}, {{"All_Rows", each _, type table [Team=nullable text, abbreviation=nullable text, assist_percentage=nullable number, assists=nullable number, away_losses=nullable number, away_wins=nullable number, block_percentage=nullable number, blocks=nullable number, conference=nullable text, conference_losses=nullable number, conference_wins=nullable number, defensive_rebounds=nullable number, effective_field_goal_percentage=nullable number, field_goal_attempts=nullable number, field_goal_percentage=nullable number, field_goals=nullable number, free_throw_attempt_rate=nullable number, free_throw_attempts=nullable number, free_throw_percentage=nullable number, free_throws=nullable number, free_throws_per_field_goal_attempt=nullable number, games_played=nullable number, home_losses=nullable number, home_wins=nullable number, losses=nullable number, minutes_played=nullable number, name=nullable text, net_rating=nullable text, offensive_rating=nullable number, offensive_rebound_percentage=nullable number, offensive_rebounds=nullable number, opp_assist_percentage=nullable number, opp_assists=nullable number, opp_block_percentage=nullable number, opp_blocks=nullable number, opp_defensive_rebounds=nullable number, opp_effective_field_goal_percentage=nullable number, opp_field_goal_attempts=nullable number, opp_field_goal_percentage=nullable number, opp_field_goals=nullable number, opp_free_throw_attempt_rate=nullable number, opp_free_throw_attempts=nullable number, opp_free_throw_percentage=nullable number, opp_free_throws=nullable number, opp_free_throws_per_field_goal_attempt=nullable number, opp_offensive_rating=nullable text, opp_offensive_rebound_percentage=nullable number, opp_offensive_rebounds=nullable number, opp_personal_fouls=nullable number, opp_points=nullable number, opp_steal_percentage=nullable number, opp_steals=nullable number, opp_three_point_attempt_rate=nullable number, opp_three_point_field_goal_attempts=nullable number, opp_three_point_field_goal_percentage=nullable number, opp_three_point_field_goals=nullable number, opp_two_point_field_goal_attempts=nullable number, opp_two_point_field_goal_percentage=nullable number, opp_two_point_field_goals=nullable number, opp_total_rebound_percentage=nullable number, opp_total_rebounds=nullable number, opp_true_shooting_percentage=nullable number, opp_turnover_percentage=nullable number, opp_turnovers=nullable number, pace=nullable number, personal_fouls=nullable number, points=nullable number, simple_rating_system=nullable number, steal_percentage=nullable number, steals=nullable number, strength_of_schedule=nullable number, three_point_attempt_rate=nullable number, three_point_field_goal_attempts=nullable number, three_point_field_goal_percentage=nullable number, three_point_field_goals=nullable number, two_point_field_goal_attempts=nullable number, two_point_field_goal_percentage=nullable number, two_point_field_goals=nullable number, total_rebound_percentage=nullable number, total_rebounds=nullable number, true_shooting_percentage=nullable number, turnover_percentage=nullable number, turnovers=nullable number, win_percentage=nullable number, wins=nullable number, Year=nullable number]}}),
    #"Ranked_assist_percentage" = Table.TransformColumns(#"Grouped Rows", {"All_Rows", each Ranked_Functions(_,"assist_percentage","DESC")}),
    #"Ranked_assists" = Table.TransformColumns(#"Ranked_assist_percentage", {"All_Rows", each Ranked_Functions(_,"assists","DESC")}),
    #"Ranked_away_losses" = Table.TransformColumns(#"Ranked_assists", {"All_Rows", each Ranked_Functions(_,"away_losses","ASC")}),
    #"Ranked_away_wins" = Table.TransformColumns(#"Ranked_away_losses", {"All_Rows", each Ranked_Functions(_,"away_wins","DESC")}),
    #"Ranked_block_percentage" = Table.TransformColumns(#"Ranked_away_wins", {"All_Rows", each Ranked_Functions(_,"block_percentage","DESC")}),
    #"Ranked_blocks" = Table.TransformColumns(#"Ranked_block_percentage", {"All_Rows", each Ranked_Functions(_,"blocks","DESC")}),
    #"Ranked_conference_losses" = Table.TransformColumns(#"Ranked_blocks", {"All_Rows", each Ranked_Functions(_,"conference_losses","ASC")}),
    #"Ranked_conference_wins" = Table.TransformColumns(#"Ranked_conference_losses", {"All_Rows", each Ranked_Functions(_,"conference_wins","DESC")}),
    #"Ranked_defensive_rebounds" = Table.TransformColumns(#"Ranked_conference_wins", {"All_Rows", each Ranked_Functions(_,"defensive_rebounds","DESC")}),
    #"Ranked_effective_field_goal_percentage" = Table.TransformColumns(#"Ranked_defensive_rebounds", {"All_Rows", each Ranked_Functions(_,"effective_field_goal_percentage","DESC")}),
    #"Ranked_field_goal_attempts" = Table.TransformColumns(#"Ranked_effective_field_goal_percentage", {"All_Rows", each Ranked_Functions(_,"field_goal_attempts","DESC")}),
    #"Ranked_field_goal_percentage" = Table.TransformColumns(#"Ranked_field_goal_attempts", {"All_Rows", each Ranked_Functions(_,"field_goal_percentage","DESC")}),
    #"Ranked_field_goals" = Table.TransformColumns(#"Ranked_field_goal_percentage", {"All_Rows", each Ranked_Functions(_,"field_goals","DESC")}),
    #"Ranked_free_throw_attempt_rate" = Table.TransformColumns(#"Ranked_field_goals", {"All_Rows", each Ranked_Functions(_,"free_throw_attempt_rate","DESC")}),
    #"Ranked_free_throw_attempts" = Table.TransformColumns(#"Ranked_free_throw_attempt_rate", {"All_Rows", each Ranked_Functions(_,"free_throw_attempts","DESC")}),
    #"Ranked_free_throw_percentage" = Table.TransformColumns(#"Ranked_free_throw_attempts", {"All_Rows", each Ranked_Functions(_,"free_throw_percentage","DESC")}),
    #"Ranked_free_throws" = Table.TransformColumns(#"Ranked_free_throw_percentage", {"All_Rows", each Ranked_Functions(_,"free_throws","DESC")}),
    #"Ranked_free_throws_per_field_goal_attempt" = Table.TransformColumns(#"Ranked_free_throws", {"All_Rows", each Ranked_Functions(_,"free_throws_per_field_goal_attempt","DESC")}),
    #"Ranked_games_played" = Table.TransformColumns(#"Ranked_free_throws_per_field_goal_attempt", {"All_Rows", each Ranked_Functions(_,"games_played","DESC")}),
    #"Ranked_home_losses" = Table.TransformColumns(#"Ranked_games_played", {"All_Rows", each Ranked_Functions(_,"home_losses","ASC")}),
    #"Ranked_home_wins" = Table.TransformColumns(#"Ranked_home_losses", {"All_Rows", each Ranked_Functions(_,"home_wins","DESC")}),
    #"Ranked_losses" = Table.TransformColumns(#"Ranked_home_wins", {"All_Rows", each Ranked_Functions(_,"losses","ASC")}),
    #"Ranked_minutes_played" = Table.TransformColumns(#"Ranked_losses", {"All_Rows", each Ranked_Functions(_,"minutes_played","DESC")}),
    #"Ranked_offensive_rating" = Table.TransformColumns(#"Ranked_minutes_played", {"All_Rows", each Ranked_Functions(_,"offensive_rating","DESC")}),
    #"Ranked_offensive_rebound_percentage" = Table.TransformColumns(#"Ranked_offensive_rating", {"All_Rows", each Ranked_Functions(_,"offensive_rebound_percentage","DESC")}),
    #"Ranked_offensive_rebounds" = Table.TransformColumns(#"Ranked_offensive_rebound_percentage", {"All_Rows", each Ranked_Functions(_,"offensive_rebounds","DESC")}),
    #"Ranked_opp_assist_percentage" = Table.TransformColumns(#"Ranked_offensive_rebounds", {"All_Rows", each Ranked_Functions(_,"opp_assist_percentage","ASC")}),
    #"Ranked_opp_assists" = Table.TransformColumns(#"Ranked_opp_assist_percentage", {"All_Rows", each Ranked_Functions(_,"opp_assists","ASC")}),
    #"Ranked_opp_block_percentage" = Table.TransformColumns(#"Ranked_opp_assists", {"All_Rows", each Ranked_Functions(_,"opp_block_percentage","ASC")}),
    #"Ranked_opp_blocks" = Table.TransformColumns(#"Ranked_opp_block_percentage", {"All_Rows", each Ranked_Functions(_,"opp_blocks","ASC")}),
    #"Ranked_opp_defensive_rebounds" = Table.TransformColumns(#"Ranked_opp_blocks", {"All_Rows", each Ranked_Functions(_,"opp_defensive_rebounds","ASC")}),
    #"Ranked_opp_effective_field_goal_percentage" = Table.TransformColumns(#"Ranked_opp_defensive_rebounds", {"All_Rows", each Ranked_Functions(_,"opp_effective_field_goal_percentage","ASC")}),
    #"Ranked_opp_field_goal_attempts" = Table.TransformColumns(#"Ranked_opp_effective_field_goal_percentage", {"All_Rows", each Ranked_Functions(_,"opp_field_goal_attempts","ASC")}),
    #"Ranked_opp_field_goal_percentage" = Table.TransformColumns(#"Ranked_opp_field_goal_attempts", {"All_Rows", each Ranked_Functions(_,"opp_field_goal_percentage","ASC")}),
    #"Ranked_opp_field_goals" = Table.TransformColumns(#"Ranked_opp_field_goal_percentage", {"All_Rows", each Ranked_Functions(_,"opp_field_goals","ASC")}),
    #"Ranked_opp_free_throw_attempt_rate" = Table.TransformColumns(#"Ranked_opp_field_goals", {"All_Rows", each Ranked_Functions(_,"opp_free_throw_attempt_rate","ASC")}),
    #"Ranked_opp_free_throw_attempts" = Table.TransformColumns(#"Ranked_opp_free_throw_attempt_rate", {"All_Rows", each Ranked_Functions(_,"opp_free_throw_attempts","ASC")}),
    #"Ranked_opp_free_throw_percentage" = Table.TransformColumns(#"Ranked_opp_free_throw_attempts", {"All_Rows", each Ranked_Functions(_,"opp_free_throw_percentage","ASC")}),
    #"Ranked_opp_free_throws" = Table.TransformColumns(#"Ranked_opp_free_throw_percentage", {"All_Rows", each Ranked_Functions(_,"opp_free_throws","ASC")}),
    #"Ranked_opp_free_throws_per_field_goal_attempt" = Table.TransformColumns(#"Ranked_opp_free_throws", {"All_Rows", each Ranked_Functions(_,"opp_free_throws_per_field_goal_attempt","ASC")}),
    #"Ranked_opp_offensive_rebound_percentage" = Table.TransformColumns(#"Ranked_opp_free_throws_per_field_goal_attempt", {"All_Rows", each Ranked_Functions(_,"opp_offensive_rebound_percentage","ASC")}),
    #"Ranked_opp_offensive_rebounds" = Table.TransformColumns(#"Ranked_opp_offensive_rebound_percentage", {"All_Rows", each Ranked_Functions(_,"opp_offensive_rebounds","ASC")}),
    #"Ranked_opp_personal_fouls" = Table.TransformColumns(#"Ranked_opp_offensive_rebounds", {"All_Rows", each Ranked_Functions(_,"opp_personal_fouls","DESC")}),
    #"Ranked_opp_points" = Table.TransformColumns(#"Ranked_opp_personal_fouls", {"All_Rows", each Ranked_Functions(_,"opp_points","ASC")}),
    #"Ranked_opp_steal_percentage" = Table.TransformColumns(#"Ranked_opp_points", {"All_Rows", each Ranked_Functions(_,"opp_steal_percentage","ASC")}),
    #"Ranked_opp_steals" = Table.TransformColumns(#"Ranked_opp_steal_percentage", {"All_Rows", each Ranked_Functions(_,"opp_steals","ASC")}),
    #"Ranked_opp_three_point_attempt_rate" = Table.TransformColumns(#"Ranked_opp_steals", {"All_Rows", each Ranked_Functions(_,"opp_three_point_attempt_rate","ASC")}),
    #"Ranked_opp_three_point_field_goal_attempts" = Table.TransformColumns(#"Ranked_opp_three_point_attempt_rate", {"All_Rows", each Ranked_Functions(_,"opp_three_point_field_goal_attempts","ASC")}),
    #"Ranked_opp_three_point_field_goal_percentage" = Table.TransformColumns(#"Ranked_opp_three_point_field_goal_attempts", {"All_Rows", each Ranked_Functions(_,"opp_three_point_field_goal_percentage","ASC")}),
    #"Ranked_opp_three_point_field_goals" = Table.TransformColumns(#"Ranked_opp_three_point_field_goal_percentage", {"All_Rows", each Ranked_Functions(_,"opp_three_point_field_goals","ASC")}),
    #"Ranked_opp_two_point_field_goal_attempts" = Table.TransformColumns(#"Ranked_opp_three_point_field_goals", {"All_Rows", each Ranked_Functions(_,"opp_two_point_field_goal_attempts","ASC")}),
    #"Ranked_opp_two_point_field_goal_percentage" = Table.TransformColumns(#"Ranked_opp_two_point_field_goal_attempts", {"All_Rows", each Ranked_Functions(_,"opp_two_point_field_goal_percentage","ASC")}),
    #"Ranked_opp_two_point_field_goals" = Table.TransformColumns(#"Ranked_opp_two_point_field_goal_percentage", {"All_Rows", each Ranked_Functions(_,"opp_two_point_field_goals","ASC")}),
    #"Ranked_opp_total_rebound_percentage" = Table.TransformColumns(#"Ranked_opp_two_point_field_goals", {"All_Rows", each Ranked_Functions(_,"opp_total_rebound_percentage","ASC")}),
    #"Ranked_opp_total_rebounds" = Table.TransformColumns(#"Ranked_opp_total_rebound_percentage", {"All_Rows", each Ranked_Functions(_,"opp_total_rebounds","ASC")}),
    #"Ranked_opp_true_shooting_percentage" = Table.TransformColumns(#"Ranked_opp_total_rebounds", {"All_Rows", each Ranked_Functions(_,"opp_true_shooting_percentage","ASC")}),
    #"Ranked_opp_turnover_percentage" = Table.TransformColumns(#"Ranked_opp_true_shooting_percentage", {"All_Rows", each Ranked_Functions(_,"opp_turnover_percentage","DESC")}),
    #"Ranked_opp_turnovers" = Table.TransformColumns(#"Ranked_opp_turnover_percentage", {"All_Rows", each Ranked_Functions(_,"opp_turnovers","DESC")}),
    #"Ranked_personal_fouls" = Table.TransformColumns(#"Ranked_opp_turnovers", {"All_Rows", each Ranked_Functions(_,"personal_fouls","ASC")}),
    #"Ranked_points" = Table.TransformColumns(#"Ranked_personal_fouls", {"All_Rows", each Ranked_Functions(_,"points","DESC")}),
    #"Ranked_steal_percentage" = Table.TransformColumns(#"Ranked_points", {"All_Rows", each Ranked_Functions(_,"steal_percentage","DESC")}),
    #"Ranked_steals" = Table.TransformColumns(#"Ranked_steal_percentage", {"All_Rows", each Ranked_Functions(_,"steals","DESC")}),
    #"Ranked_strength_of_schedule" = Table.TransformColumns(#"Ranked_steals", {"All_Rows", each Ranked_Functions(_,"strength_of_schedule","DESC")}),
    #"Ranked_three_point_field_goal_percentage" = Table.TransformColumns(#"Ranked_strength_of_schedule", {"All_Rows", each Ranked_Functions(_,"three_point_field_goal_percentage","DESC")}),
    #"Ranked_three_point_field_goal_attempts" = Table.TransformColumns(#"Ranked_three_point_field_goal_percentage", {"All_Rows", each Ranked_Functions(_,"three_point_field_goal_attempts","DESC")}),
    #"Ranked_three_point_field_goals" = Table.TransformColumns(#"Ranked_three_point_field_goal_attempts", {"All_Rows", each Ranked_Functions(_,"three_point_field_goals","DESC")}),
    #"Ranked_two_point_field_goal_attempts" = Table.TransformColumns(#"Ranked_three_point_field_goals", {"All_Rows", each Ranked_Functions(_,"two_point_field_goal_attempts","DESC")}),
    #"Ranked_two_point_field_goal_percentage" = Table.TransformColumns(#"Ranked_two_point_field_goal_attempts", {"All_Rows", each Ranked_Functions(_,"two_point_field_goal_percentage","DESC")}),
    #"Ranked_two_point_field_goals" = Table.TransformColumns(#"Ranked_two_point_field_goal_percentage", {"All_Rows", each Ranked_Functions(_,"two_point_field_goals","DESC")}),
    #"Ranked_total_rebound_percentage" = Table.TransformColumns(#"Ranked_two_point_field_goals", {"All_Rows", each Ranked_Functions(_,"total_rebound_percentage","DESC")}),
    #"Ranked_total_rebounds" = Table.TransformColumns(#"Ranked_total_rebound_percentage", {"All_Rows", each Ranked_Functions(_,"total_rebounds","DESC")}),
    #"Ranked_true_shooting_percentage" = Table.TransformColumns(#"Ranked_total_rebounds", {"All_Rows", each Ranked_Functions(_,"true_shooting_percentage","DESC")}),
    #"Ranked_turnover_percentage" = Table.TransformColumns(#"Ranked_true_shooting_percentage", {"All_Rows", each Ranked_Functions(_,"turnover_percentage","ASC")}),
    #"Ranked_turnovers" = Table.TransformColumns(#"Ranked_turnover_percentage", {"All_Rows", each Ranked_Functions(_,"turnovers","ASC")}),
    #"Ranked_win_percentage" = Table.TransformColumns(#"Ranked_turnovers", {"All_Rows", each Ranked_Functions(_,"win_percentage","DESC")}),
    #"Ranked_wins" = Table.TransformColumns(#"Ranked_win_percentage", {"All_Rows", each Ranked_Functions(_,"wins","DESC")}),
    #"Ranked_points_per_game" = Table.TransformColumns(#"Ranked_wins", {"All_Rows", each Ranked_Functions(_,"points_per_game","DESC")}),
    #"Ranked_opp_points_per_game" = Table.TransformColumns(#"Ranked_points_per_game", {"All_Rows", each Ranked_Functions(_,"opp_points_per_game","ASC")}), 
    #"Ranked_assists_per_game" = Table.TransformColumns(#"Ranked_opp_points_per_game", {"All_Rows", each Ranked_Functions(_,"assists_per_game","DESC")}),
    #"Ranked_opp_assists_per_game" = Table.TransformColumns(#"Ranked_assists_per_game", {"All_Rows", each Ranked_Functions(_,"opp_assists_per_game","ASC")}),
    #"Ranked_blocks_per_game" = Table.TransformColumns(#"Ranked_opp_assists_per_game", {"All_Rows", each Ranked_Functions(_,"blocks_per_game","DESC")}),
    #"Ranked_opp_blocks_per_game" = Table.TransformColumns(#"Ranked_blocks_per_game", {"All_Rows", each Ranked_Functions(_,"opp_blocks_per_game","ASC")}),
    #"Ranked_defensive_rebounds_per_game" = Table.TransformColumns(#"Ranked_opp_blocks_per_game", {"All_Rows", each Ranked_Functions(_,"defensive_rebounds_per_game","DESC")}),
    #"Ranked_opp_defensive_rebounds_per_game" = Table.TransformColumns(#"Ranked_defensive_rebounds_per_game", {"All_Rows", each Ranked_Functions(_,"opp_defensive_rebounds_per_game","ASC")}),
    #"Ranked_field_goal_attempts_per_game" = Table.TransformColumns(#"Ranked_opp_defensive_rebounds_per_game", {"All_Rows", each Ranked_Functions(_,"field_goal_attempts_per_game","DESC")}),
    #"Ranked_opp_field_goal_attempts_per_game" = Table.TransformColumns(#"Ranked_field_goal_attempts_per_game", {"All_Rows", each Ranked_Functions(_,"opp_field_goal_attempts_per_game","ASC")}),
    #"Ranked_free_throw_attempts_per_game" = Table.TransformColumns(#"Ranked_opp_field_goal_attempts_per_game", {"All_Rows", each Ranked_Functions(_,"free_throw_attempts_per_game","DESC")}),
    #"Ranked_opp_free_throw_attempts_per_game" = Table.TransformColumns(#"Ranked_free_throw_attempts_per_game", {"All_Rows", each Ranked_Functions(_,"opp_free_throw_attempts_per_game","ASC")}),
    #"Ranked_free_throws_per_game" = Table.TransformColumns(#"Ranked_opp_free_throw_attempts_per_game", {"All_Rows", each Ranked_Functions(_,"free_throws_per_game","DESC")}),
    #"Ranked_opp_free_throws_per_game" = Table.TransformColumns(#"Ranked_free_throws_per_game", {"All_Rows", each Ranked_Functions(_,"opp_free_throws_per_game","ASC")}),
    #"Ranked_offensive_rebounds_per_game" = Table.TransformColumns(#"Ranked_opp_free_throws_per_game", {"All_Rows", each Ranked_Functions(_,"offensive_rebounds_per_game","DESC")}),
    #"Ranked_opp_offensive_rebounds_per_game" = Table.TransformColumns(#"Ranked_offensive_rebounds_per_game", {"All_Rows", each Ranked_Functions(_,"opp_offensive_rebounds_per_game","ASC")}),
    #"Ranked_personal_fouls_per_game" = Table.TransformColumns(#"Ranked_opp_offensive_rebounds_per_game", {"All_Rows", each Ranked_Functions(_,"personal_fouls_per_game","ASC")}),
    #"Ranked_opp_personal_fouls_per_game" = Table.TransformColumns(#"Ranked_personal_fouls_per_game", {"All_Rows", each Ranked_Functions(_,"opp_personal_fouls_per_game","DESC")}),
    #"Ranked_steals_per_game" = Table.TransformColumns(#"Ranked_opp_personal_fouls_per_game", {"All_Rows", each Ranked_Functions(_,"steals_per_game","DESC")}),
    #"Ranked_opp_steals_per_game" = Table.TransformColumns(#"Ranked_steals_per_game", {"All_Rows", each Ranked_Functions(_,"opp_steals_per_game","ASC")}),
    #"Ranked_three_point_field_goal_attempts_per_game" = Table.TransformColumns(#"Ranked_opp_steals_per_game", {"All_Rows", each Ranked_Functions(_,"three_point_field_goal_attempts_per_game","DESC")}),
    #"Ranked_opp_three_point_field_goal_attempts_per_game" = Table.TransformColumns(#"Ranked_three_point_field_goal_attempts_per_game", {"All_Rows", each Ranked_Functions(_,"opp_three_point_field_goal_attempts_per_game","ASC")}),
    #"Ranked_three_point_field_goals_per_game" = Table.TransformColumns(#"Ranked_opp_three_point_field_goal_attempts_per_game", {"All_Rows", each Ranked_Functions(_,"three_point_field_goals_per_game","DESC")}),
    #"Ranked_opp_three_point_field_goals_per_game" = Table.TransformColumns(#"Ranked_three_point_field_goals_per_game", {"All_Rows", each Ranked_Functions(_,"opp_three_point_field_goals_per_game","ASC")}),
    #"Ranked_two_point_field_goal_attempts_per_game" = Table.TransformColumns(#"Ranked_opp_three_point_field_goals_per_game", {"All_Rows", each Ranked_Functions(_,"two_point_field_goal_attempts_per_game","DESC")}),
    #"Ranked_opp_two_point_field_goal_attempts_per_game" = Table.TransformColumns(#"Ranked_two_point_field_goal_attempts_per_game", {"All_Rows", each Ranked_Functions(_,"opp_two_point_field_goal_attempts_per_game","ASC")}),
    #"Ranked_two_point_field_goals_per_game" = Table.TransformColumns(#"Ranked_opp_two_point_field_goal_attempts_per_game", {"All_Rows", each Ranked_Functions(_,"two_point_field_goals_per_game","DESC")}),
    #"Ranked_opp_two_point_field_goals_per_game" = Table.TransformColumns(#"Ranked_two_point_field_goals_per_game", {"All_Rows", each Ranked_Functions(_,"opp_two_point_field_goals_per_game","ASC")}),
    #"Ranked_total_rebounds_per_game" = Table.TransformColumns(#"Ranked_opp_two_point_field_goals_per_game", {"All_Rows", each Ranked_Functions(_,"total_rebounds_per_game","DESC")}),
    #"Ranked_opp_total_rebounds_per_game" = Table.TransformColumns(#"Ranked_total_rebounds_per_game", {"All_Rows", each Ranked_Functions(_,"opp_total_rebounds_per_game","ASC")}),
    #"Ranked_turnovers_per_game" = Table.TransformColumns(#"Ranked_opp_total_rebounds_per_game", {"All_Rows", each Ranked_Functions(_,"turnovers_per_game","ASC")}),
    #"Ranked_opp_turnovers_per_game" = Table.TransformColumns(#"Ranked_turnovers_per_game", {"All_Rows", each Ranked_Functions(_,"opp_turnovers_per_game","DESC")}),
    #"Expanded All_Rows" = Table.ExpandTableColumn(Ranked_opp_turnovers_per_game, "All_Rows", {"Team", "Ranked_assist_percentage", "Ranked_assists", "Ranked_away_losses", "Ranked_away_wins", "Ranked_block_percentage", "Ranked_blocks", "Ranked_conference_losses", "Ranked_conference_wins", "Ranked_defensive_rebounds", "Ranked_effective_field_goal_percentage", "Ranked_field_goal_attempts", "Ranked_field_goal_percentage", "Ranked_field_goals", "Ranked_free_throw_attempt_rate", "Ranked_free_throw_attempts", "Ranked_free_throw_percentage", "Ranked_free_throws", "Ranked_free_throws_per_field_goal_attempt", "Ranked_games_played", "Ranked_home_losses", "Ranked_home_wins", "Ranked_losses", "Ranked_minutes_played", "Ranked_offensive_rating", "Ranked_offensive_rebound_percentage", "Ranked_offensive_rebounds", "Ranked_opp_assist_percentage", "Ranked_opp_assists", "Ranked_opp_block_percentage", "Ranked_opp_blocks", "Ranked_opp_defensive_rebounds", "Ranked_opp_effective_field_goal_percentage", "Ranked_opp_field_goal_attempts", "Ranked_opp_field_goal_percentage", "Ranked_opp_field_goals", "Ranked_opp_free_throw_attempt_rate", "Ranked_opp_free_throw_attempts", "Ranked_opp_free_throw_percentage", "Ranked_opp_free_throws", "Ranked_opp_free_throws_per_field_goal_attempt", "Ranked_opp_offensive_rebound_percentage", "Ranked_opp_offensive_rebounds", "Ranked_opp_personal_fouls", "Ranked_opp_points", "Ranked_opp_steal_percentage", "Ranked_opp_steals", "Ranked_opp_three_point_attempt_rate", "Ranked_opp_three_point_field_goal_attempts", "Ranked_opp_three_point_field_goal_percentage", "Ranked_opp_three_point_field_goals", "Ranked_opp_two_point_field_goal_attempts", "Ranked_opp_two_point_field_goal_percentage", "Ranked_opp_two_point_field_goals", "Ranked_opp_total_rebound_percentage", "Ranked_opp_total_rebounds", "Ranked_opp_true_shooting_percentage", "Ranked_opp_turnover_percentage", "Ranked_opp_turnovers", "Ranked_personal_fouls", "Ranked_points", "Ranked_steal_percentage", "Ranked_steals", "Ranked_strength_of_schedule", "Ranked_three_point_field_goal_percentage", "Ranked_three_point_field_goal_attempts", "Ranked_three_point_field_goals", "Ranked_two_point_field_goal_attempts", "Ranked_two_point_field_goal_percentage", "Ranked_two_point_field_goals", "Ranked_total_rebound_percentage", "Ranked_total_rebounds", "Ranked_true_shooting_percentage", "Ranked_turnover_percentage", "Ranked_turnovers", "Ranked_win_percentage", "Ranked_wins", "Ranked_points_per_game", "Ranked_opp_points_per_game", "Ranked_assists_per_game", "Ranked_opp_assists_per_game", "Ranked_blocks_per_game", "Ranked_opp_blocks_per_game", "Ranked_defensive_rebounds_per_game", "Ranked_opp_defensive_rebounds_per_game", "Ranked_field_goal_attempts_per_game", "Ranked_opp_field_goal_attempts_per_game", "Ranked_free_throw_attempts_per_game", "Ranked_opp_free_throw_attempts_per_game", "Ranked_free_throws_per_game", "Ranked_opp_free_throws_per_game", "Ranked_offensive_rebounds_per_game", "Ranked_opp_offensive_rebounds_per_game", "Ranked_personal_fouls_per_game", "Ranked_opp_personal_fouls_per_game", "Ranked_steals_per_game", "Ranked_opp_steals_per_game", "Ranked_three_point_field_goal_attempts_per_game", "Ranked_opp_three_point_field_goal_attempts_per_game", "Ranked_three_point_field_goals_per_game", "Ranked_opp_three_point_field_goals_per_game", "Ranked_two_point_field_goal_attempts_per_game", "Ranked_opp_two_point_field_goal_attempts_per_game", "Ranked_two_point_field_goals_per_game", "Ranked_opp_two_point_field_goals_per_game", "Ranked_total_rebounds_per_game", "Ranked_opp_total_rebounds_per_game", "Ranked_turnovers_per_game", "Ranked_opp_turnovers_per_game"}, {"Team", "Ranked_assist_percentage", "Ranked_assists", "Ranked_away_losses", "Ranked_away_wins", "Ranked_block_percentage", "Ranked_blocks", "Ranked_conference_losses", "Ranked_conference_wins", "Ranked_defensive_rebounds", "Ranked_effective_field_goal_percentage", "Ranked_field_goal_attempts", "Ranked_field_goal_percentage", "Ranked_field_goals", "Ranked_free_throw_attempt_rate", "Ranked_free_throw_attempts", "Ranked_free_throw_percentage", "Ranked_free_throws", "Ranked_free_throws_per_field_goal_attempt", "Ranked_games_played", "Ranked_home_losses", "Ranked_home_wins", "Ranked_losses", "Ranked_minutes_played", "Ranked_offensive_rating", "Ranked_offensive_rebound_percentage", "Ranked_offensive_rebounds", "Ranked_opp_assist_percentage", "Ranked_opp_assists", "Ranked_opp_block_percentage", "Ranked_opp_blocks", "Ranked_opp_defensive_rebounds", "Ranked_opp_effective_field_goal_percentage", "Ranked_opp_field_goal_attempts", "Ranked_opp_field_goal_percentage", "Ranked_opp_field_goals", "Ranked_opp_free_throw_attempt_rate", "Ranked_opp_free_throw_attempts", "Ranked_opp_free_throw_percentage", "Ranked_opp_free_throws", "Ranked_opp_free_throws_per_field_goal_attempt", "Ranked_opp_offensive_rebound_percentage", "Ranked_opp_offensive_rebounds", "Ranked_opp_personal_fouls", "Ranked_opp_points", "Ranked_opp_steal_percentage", "Ranked_opp_steals", "Ranked_opp_three_point_attempt_rate", "Ranked_opp_three_point_field_goal_attempts", "Ranked_opp_three_point_field_goal_percentage", "Ranked_opp_three_point_field_goals", "Ranked_opp_two_point_field_goal_attempts", "Ranked_opp_two_point_field_goal_percentage", "Ranked_opp_two_point_field_goals", "Ranked_opp_total_rebound_percentage", "Ranked_opp_total_rebounds", "Ranked_opp_true_shooting_percentage", "Ranked_opp_turnover_percentage", "Ranked_opp_turnovers", "Ranked_personal_fouls", "Ranked_points", "Ranked_steal_percentage", "Ranked_steals", "Ranked_strength_of_schedule", "Ranked_three_point_field_goal_percentage", "Ranked_three_point_field_goal_attempts", "Ranked_three_point_field_goals", "Ranked_two_point_field_goal_attempts", "Ranked_two_point_field_goal_percentage", "Ranked_two_point_field_goals", "Ranked_total_rebound_percentage", "Ranked_total_rebounds", "Ranked_true_shooting_percentage", "Ranked_turnover_percentage", "Ranked_turnovers", "Ranked_win_percentage", "Ranked_wins", "Ranked_points_per_game", "Ranked_opp_points_per_game", "Ranked_assists_per_game", "Ranked_opp_assists_per_game", "Ranked_blocks_per_game", "Ranked_opp_blocks_per_game", "Ranked_defensive_rebounds_per_game", "Ranked_opp_defensive_rebounds_per_game", "Ranked_field_goal_attempts_per_game", "Ranked_opp_field_goal_attempts_per_game", "Ranked_free_throw_attempts_per_game", "Ranked_opp_free_throw_attempts_per_game", "Ranked_free_throws_per_game", "Ranked_opp_free_throws_per_game", "Ranked_offensive_rebounds_per_game", "Ranked_opp_offensive_rebounds_per_game", "Ranked_personal_fouls_per_game", "Ranked_opp_personal_fouls_per_game", "Ranked_steals_per_game", "Ranked_opp_steals_per_game", "Ranked_three_point_field_goal_attempts_per_game", "Ranked_opp_three_point_field_goal_attempts_per_game", "Ranked_three_point_field_goals_per_game", "Ranked_opp_three_point_field_goals_per_game", "Ranked_two_point_field_goal_attempts_per_game", "Ranked_opp_two_point_field_goal_attempts_per_game", "Ranked_two_point_field_goals_per_game", "Ranked_opp_two_point_field_goals_per_game", "Ranked_total_rebounds_per_game", "Ranked_opp_total_rebounds_per_game", "Ranked_turnovers_per_game", "Ranked_opp_turnovers_per_game"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded All_Rows",{{"Ranked_opp_points_per_game", Int64.Type}, {"Ranked_points_per_game", Int64.Type}, {"Ranked_wins", Int64.Type}, {"Ranked_win_percentage", Int64.Type}, {"Ranked_turnovers", Int64.Type}, {"Ranked_turnover_percentage", Int64.Type}, {"Ranked_true_shooting_percentage", Int64.Type}, {"Ranked_total_rebounds", Int64.Type}, {"Ranked_total_rebound_percentage", Int64.Type}, {"Ranked_two_point_field_goals", Int64.Type}, {"Ranked_two_point_field_goal_percentage", Int64.Type}, {"Ranked_two_point_field_goal_attempts", Int64.Type}, {"Ranked_three_point_field_goals", Int64.Type}, {"Ranked_three_point_field_goal_attempts", Int64.Type}, {"Ranked_three_point_field_goal_percentage", Int64.Type}, {"Ranked_strength_of_schedule", Int64.Type}, {"Ranked_steals", Int64.Type}, {"Ranked_steal_percentage", Int64.Type}, {"Ranked_points", Int64.Type}, {"Ranked_personal_fouls", Int64.Type}, {"Ranked_opp_turnovers", Int64.Type}, {"Ranked_opp_turnover_percentage", Int64.Type}, {"Ranked_opp_true_shooting_percentage", Int64.Type}, {"Ranked_opp_total_rebounds", Int64.Type}, {"Ranked_opp_total_rebound_percentage", Int64.Type}, {"Ranked_opp_two_point_field_goals", Int64.Type}, {"Ranked_opp_two_point_field_goal_percentage", Int64.Type}, {"Ranked_opp_two_point_field_goal_attempts", Int64.Type}, {"Ranked_opp_three_point_field_goals", Int64.Type}, {"Ranked_opp_three_point_field_goal_percentage", Int64.Type}, {"Ranked_opp_three_point_field_goal_attempts", Int64.Type}, {"Ranked_opp_three_point_attempt_rate", Int64.Type}, {"Ranked_opp_steals", Int64.Type}, {"Ranked_opp_steal_percentage", Int64.Type}, {"Ranked_opp_points", Int64.Type}, {"Ranked_opp_personal_fouls", Int64.Type}, {"Ranked_opp_offensive_rebounds", Int64.Type}, {"Ranked_opp_offensive_rebound_percentage", Int64.Type}, {"Ranked_opp_free_throws_per_field_goal_attempt", Int64.Type}, {"Ranked_opp_free_throws", Int64.Type}, {"Ranked_opp_free_throw_percentage", Int64.Type}, {"Ranked_opp_free_throw_attempts", Int64.Type}, {"Ranked_opp_free_throw_attempt_rate", Int64.Type}, {"Ranked_opp_field_goals", Int64.Type}, {"Ranked_opp_field_goal_percentage", Int64.Type}, {"Ranked_opp_field_goal_attempts", Int64.Type}, {"Ranked_opp_effective_field_goal_percentage", Int64.Type}, {"Ranked_opp_defensive_rebounds", Int64.Type}, {"Ranked_opp_blocks", Int64.Type}, {"Ranked_opp_block_percentage", Int64.Type}, {"Ranked_opp_assists", Int64.Type}, {"Ranked_opp_assist_percentage", Int64.Type}, {"Ranked_offensive_rebounds", Int64.Type}, {"Ranked_offensive_rebound_percentage", Int64.Type}, {"Ranked_offensive_rating", Int64.Type}, {"Ranked_minutes_played", Int64.Type}, {"Ranked_losses", Int64.Type}, {"Ranked_home_wins", Int64.Type}, {"Ranked_home_losses", Int64.Type}, {"Ranked_games_played", Int64.Type}, {"Ranked_free_throws_per_field_goal_attempt", Int64.Type}, {"Ranked_free_throws", Int64.Type}, {"Ranked_free_throw_percentage", Int64.Type}, {"Ranked_free_throw_attempts", Int64.Type}, {"Ranked_free_throw_attempt_rate", Int64.Type}, {"Ranked_field_goals", Int64.Type}, {"Ranked_field_goal_percentage", Int64.Type}, {"Ranked_field_goal_attempts", Int64.Type}, {"Ranked_effective_field_goal_percentage", Int64.Type}, {"Ranked_defensive_rebounds", Int64.Type}, {"Ranked_conference_wins", Int64.Type}, {"Ranked_conference_losses", Int64.Type}, {"Ranked_blocks", Int64.Type}, {"Ranked_block_percentage", Int64.Type}, {"Ranked_away_wins", Int64.Type}, {"Ranked_away_losses", Int64.Type}, {"Ranked_assists", Int64.Type}, {"Ranked_assist_percentage", Int64.Type}, {"Ranked_assists_per_game", Int64.Type}, {"Ranked_opp_assists_per_game", Int64.Type}, {"Ranked_blocks_per_game", Int64.Type}, {"Ranked_opp_blocks_per_game", Int64.Type}, {"Ranked_defensive_rebounds_per_game", Int64.Type}, {"Ranked_opp_defensive_rebounds_per_game", Int64.Type}, {"Ranked_field_goal_attempts_per_game", Int64.Type}, {"Ranked_opp_field_goal_attempts_per_game", Int64.Type}, {"Ranked_free_throw_attempts_per_game", Int64.Type}, {"Ranked_opp_free_throw_attempts_per_game", Int64.Type}, {"Ranked_free_throws_per_game", Int64.Type}, {"Ranked_opp_free_throws_per_game", Int64.Type}, {"Ranked_offensive_rebounds_per_game", Int64.Type}, {"Ranked_opp_offensive_rebounds_per_game", Int64.Type}, {"Ranked_personal_fouls_per_game", Int64.Type}, {"Ranked_opp_personal_fouls_per_game", Int64.Type}, {"Ranked_steals_per_game", Int64.Type}, {"Ranked_opp_steals_per_game", Int64.Type}, {"Ranked_three_point_field_goal_attempts_per_game", Int64.Type}, {"Ranked_opp_three_point_field_goal_attempts_per_game", Int64.Type}, {"Ranked_three_point_field_goals_per_game", Int64.Type}, {"Ranked_opp_three_point_field_goals_per_game", Int64.Type}, {"Ranked_two_point_field_goal_attempts_per_game", Int64.Type}, {"Ranked_opp_two_point_field_goal_attempts_per_game", Int64.Type}, {"Ranked_two_point_field_goals_per_game", Int64.Type}, {"Ranked_opp_two_point_field_goals_per_game", Int64.Type}, {"Ranked_total_rebounds_per_game", Int64.Type}, {"Ranked_opp_total_rebounds_per_game", Int64.Type}, {"Ranked_turnovers_per_game", Int64.Type}, {"Ranked_opp_turnovers_per_game", Int64.Type}})
in
    #"Changed Type"