let
    Source = Table.Combine({#"2015_SeasonStats", #"2016_SeasonStats", #"2017_SeasonStats", #"2018_SeasonStats", #"2019_SeasonStats", #"2020_SeasonStats", #"2021_SeasonStats"}),
    #"points_per_game" = Table.AddColumn(Source, "points_per_game", each [points] / [games_played]),
    #"opp_points_per_game" = Table.AddColumn(#"points_per_game", "opp_points_per_game", each [opp_points] / [games_played]),
    #"assists_per_game" = Table.AddColumn(#"opp_points_per_game", "assists_per_game", each [assists] / [games_played]),
    #"opp_assists_per_game" = Table.AddColumn(#"assists_per_game", "opp_assists_per_game", each [opp_assists] / [games_played]),
    #"blocks_per_game" = Table.AddColumn(#"opp_assists_per_game", "blocks_per_game", each [blocks] / [games_played]),
    #"opp_blocks_per_game" = Table.AddColumn(#"blocks_per_game", "opp_blocks_per_game", each [opp_blocks] / [games_played]),
    #"defensive_rebounds_per_game" = Table.AddColumn(#"opp_blocks_per_game", "defensive_rebounds_per_game", each [defensive_rebounds] / [games_played]),
    #"opp_defensive_rebounds_per_game" = Table.AddColumn(#"defensive_rebounds_per_game", "opp_defensive_rebounds_per_game", each [opp_defensive_rebounds] / [games_played]),
    #"field_goal_attempts_per_game" = Table.AddColumn(#"opp_defensive_rebounds_per_game", "field_goal_attempts_per_game", each [field_goal_attempts] / [games_played]),
    #"opp_field_goal_attempts_per_game" = Table.AddColumn(#"field_goal_attempts_per_game", "opp_field_goal_attempts_per_game", each [opp_field_goal_attempts] / [games_played]),
    #"free_throw_attempts_per_game" = Table.AddColumn(#"opp_field_goal_attempts_per_game", "free_throw_attempts_per_game", each [free_throw_attempts] / [games_played]),
    #"opp_free_throw_attempts_per_game" = Table.AddColumn(#"free_throw_attempts_per_game", "opp_free_throw_attempts_per_game", each [opp_free_throw_attempts] / [games_played]),
    #"free_throws_per_game" = Table.AddColumn(#"opp_free_throw_attempts_per_game", "free_throws_per_game", each [free_throws] / [games_played]),
    #"opp_free_throws_per_game" = Table.AddColumn(#"free_throws_per_game", "opp_free_throws_per_game", each [opp_free_throws] / [games_played]),
    #"offensive_rebounds_per_game" = Table.AddColumn(#"opp_free_throws_per_game", "offensive_rebounds_per_game", each [offensive_rebounds] / [games_played]),
    #"opp_offensive_rebounds_per_game" = Table.AddColumn(#"offensive_rebounds_per_game", "opp_offensive_rebounds_per_game", each [opp_offensive_rebounds] / [games_played]),
    #"personal_fouls_per_game" = Table.AddColumn(#"opp_offensive_rebounds_per_game", "personal_fouls_per_game", each [personal_fouls] / [games_played]),
    #"opp_personal_fouls_per_game" = Table.AddColumn(#"personal_fouls_per_game", "opp_personal_fouls_per_game", each [opp_personal_fouls] / [games_played]),
    #"steals_per_game" = Table.AddColumn(#"opp_personal_fouls_per_game", "steals_per_game", each [steals] / [games_played]),
    #"opp_steals_per_game" = Table.AddColumn(#"steals_per_game", "opp_steals_per_game", each [opp_steals] / [games_played]),
    #"three_point_field_goal_attempts_per_game" = Table.AddColumn(#"opp_steals_per_game", "three_point_field_goal_attempts_per_game", each [three_point_field_goal_attempts] / [games_played]),
    #"opp_three_point_field_goal_attempts_per_game" = Table.AddColumn(#"three_point_field_goal_attempts_per_game", "opp_three_point_field_goal_attempts_per_game", each [opp_three_point_field_goal_attempts] / [games_played]),
    #"three_point_field_goals_per_game" = Table.AddColumn(#"opp_three_point_field_goal_attempts_per_game", "three_point_field_goals_per_game", each [three_point_field_goals] / [games_played]),
    #"opp_three_point_field_goals_per_game" = Table.AddColumn(#"three_point_field_goals_per_game", "opp_three_point_field_goals_per_game", each [opp_two_point_field_goals] / [games_played]),
    #"two_point_field_goal_attempts_per_game" = Table.AddColumn(#"opp_three_point_field_goals_per_game", "two_point_field_goal_attempts_per_game", each [two_point_field_goal_attempts] / [games_played]),
    #"opp_two_point_field_goal_attempts_per_game" = Table.AddColumn(#"two_point_field_goal_attempts_per_game", "opp_two_point_field_goal_attempts_per_game", each [opp_two_point_field_goal_attempts] / [games_played]),
    #"two_point_field_goals_per_game" = Table.AddColumn(#"opp_two_point_field_goal_attempts_per_game", "two_point_field_goals_per_game", each [two_point_field_goals] / [games_played]),
    #"opp_two_point_field_goals_per_game" = Table.AddColumn(#"two_point_field_goals_per_game", "opp_two_point_field_goals_per_game", each [opp_two_point_field_goals] / [games_played]),
    #"total_rebounds_per_game" = Table.AddColumn(#"opp_two_point_field_goals_per_game", "total_rebounds_per_game", each [total_rebounds] / [games_played]),
    #"opp_total_rebounds_per_game" = Table.AddColumn(#"total_rebounds_per_game", "opp_total_rebounds_per_game", each [opp_total_rebounds] / [games_played]),
    #"turnovers_per_game" = Table.AddColumn(#"opp_total_rebounds_per_game", "turnovers_per_game", each [turnovers] / [games_played]),
    #"opp_turnovers_per_game" = Table.AddColumn(#"turnovers_per_game", "opp_turnovers_per_game", each [opp_turnovers] / [games_played]),
    #"Changed Type" = Table.TransformColumnTypes(opp_turnovers_per_game,{{"points_per_game", type number}, {"opp_points_per_game", type number}, {"win_percentage", Percentage.Type}, {"turnover_percentage", type number}, {"true_shooting_percentage", type number}, {"total_rebound_percentage", type number}, {"two_point_field_goal_percentage", type number}, {"three_point_field_goal_percentage", type number}, {"three_point_attempt_rate", type number}, {"steal_percentage", type number}, {"opp_turnover_percentage", type number}, {"opp_true_shooting_percentage", type number}, {"opp_total_rebound_percentage", type number}, {"opp_two_point_field_goal_percentage", type number}, {"opp_three_point_field_goal_percentage", type number}, {"opp_three_point_attempt_rate", type number}, {"opp_steal_percentage", type number}, {"opp_offensive_rebound_percentage", type number}, {"opp_free_throw_percentage", type number}, {"opp_free_throw_attempt_rate", type number}, {"opp_field_goal_percentage", type number}, {"opp_effective_field_goal_percentage", type number}, {"opp_block_percentage", type number}, {"opp_assist_percentage", type number}, {"offensive_rebound_percentage", type number}, {"free_throw_percentage", type number}, {"free_throw_attempt_rate", type number}, {"field_goal_percentage", type number}, {"effective_field_goal_percentage", type number}, {"block_percentage", type number}, {"assist_percentage", type number}, {"opp_turnovers_per_game", type number}, {"turnovers_per_game", type number}, {"opp_total_rebounds_per_game", type number}, {"total_rebounds_per_game", type number}, {"opp_two_point_field_goals_per_game", type number}, {"two_point_field_goals_per_game", type number}, {"opp_two_point_field_goal_attempts_per_game", type number}, {"two_point_field_goal_attempts_per_game", type number}, {"opp_three_point_field_goals_per_game", type number}, {"three_point_field_goals_per_game", type number}, {"opp_three_point_field_goal_attempts_per_game", type number}, {"three_point_field_goal_attempts_per_game", type number}, {"opp_steals_per_game", type number}, {"steals_per_game", type number}, {"opp_personal_fouls_per_game", type number}, {"personal_fouls_per_game", type number}, {"opp_offensive_rebounds_per_game", type number}, {"offensive_rebounds_per_game", type number}, {"opp_free_throws_per_game", type number}, {"free_throws_per_game", type number}, {"opp_free_throw_attempts_per_game", type number}, {"free_throw_attempts_per_game", type number}, {"opp_field_goal_attempts_per_game", type number}, {"field_goal_attempts_per_game", type number}, {"opp_defensive_rebounds_per_game", type number}, {"defensive_rebounds_per_game", type number}, {"opp_blocks_per_game", type number}, {"blocks_per_game", type number}, {"opp_assists_per_game", type number}, {"assists_per_game", type number}})
in
    #"Changed Type"